// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package agent

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockConfigProvider creates a new instance of MockConfigProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigProvider {
	mock := &MockConfigProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfigProvider is an autogenerated mock type for the ConfigProvider type
type MockConfigProvider struct {
	mock.Mock
}

type MockConfigProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigProvider) EXPECT() *MockConfigProvider_Expecter {
	return &MockConfigProvider_Expecter{mock: &_m.Mock}
}

// Address provides a mock function for the type MockConfigProvider
func (_mock *MockConfigProvider) Address() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Address")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfigProvider_Address_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Address'
type MockConfigProvider_Address_Call struct {
	*mock.Call
}

// Address is a helper method to define mock.On call
func (_e *MockConfigProvider_Expecter) Address() *MockConfigProvider_Address_Call {
	return &MockConfigProvider_Address_Call{Call: _e.mock.On("Address")}
}

func (_c *MockConfigProvider_Address_Call) Run(run func()) *MockConfigProvider_Address_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigProvider_Address_Call) Return(s string) *MockConfigProvider_Address_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConfigProvider_Address_Call) RunAndReturn(run func() string) *MockConfigProvider_Address_Call {
	_c.Call.Return(run)
	return _c
}

// PollInterval provides a mock function for the type MockConfigProvider
func (_mock *MockConfigProvider) PollInterval() uint {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PollInterval")
	}

	var r0 uint
	if returnFunc, ok := ret.Get(0).(func() uint); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint)
	}
	return r0
}

// MockConfigProvider_PollInterval_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PollInterval'
type MockConfigProvider_PollInterval_Call struct {
	*mock.Call
}

// PollInterval is a helper method to define mock.On call
func (_e *MockConfigProvider_Expecter) PollInterval() *MockConfigProvider_PollInterval_Call {
	return &MockConfigProvider_PollInterval_Call{Call: _e.mock.On("PollInterval")}
}

func (_c *MockConfigProvider_PollInterval_Call) Run(run func()) *MockConfigProvider_PollInterval_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigProvider_PollInterval_Call) Return(v uint) *MockConfigProvider_PollInterval_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockConfigProvider_PollInterval_Call) RunAndReturn(run func() uint) *MockConfigProvider_PollInterval_Call {
	_c.Call.Return(run)
	return _c
}

// ReportInterval provides a mock function for the type MockConfigProvider
func (_mock *MockConfigProvider) ReportInterval() uint {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReportInterval")
	}

	var r0 uint
	if returnFunc, ok := ret.Get(0).(func() uint); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint)
	}
	return r0
}

// MockConfigProvider_ReportInterval_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReportInterval'
type MockConfigProvider_ReportInterval_Call struct {
	*mock.Call
}

// ReportInterval is a helper method to define mock.On call
func (_e *MockConfigProvider_Expecter) ReportInterval() *MockConfigProvider_ReportInterval_Call {
	return &MockConfigProvider_ReportInterval_Call{Call: _e.mock.On("ReportInterval")}
}

func (_c *MockConfigProvider_ReportInterval_Call) Run(run func()) *MockConfigProvider_ReportInterval_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigProvider_ReportInterval_Call) Return(v uint) *MockConfigProvider_ReportInterval_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockConfigProvider_ReportInterval_Call) RunAndReturn(run func() uint) *MockConfigProvider_ReportInterval_Call {
	_c.Call.Return(run)
	return _c
}

// SignKey provides a mock function for the type MockConfigProvider
func (_mock *MockConfigProvider) SignKey() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SignKey")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfigProvider_SignKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignKey'
type MockConfigProvider_SignKey_Call struct {
	*mock.Call
}

// SignKey is a helper method to define mock.On call
func (_e *MockConfigProvider_Expecter) SignKey() *MockConfigProvider_SignKey_Call {
	return &MockConfigProvider_SignKey_Call{Call: _e.mock.On("SignKey")}
}

func (_c *MockConfigProvider_SignKey_Call) Run(run func()) *MockConfigProvider_SignKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigProvider_SignKey_Call) Return(s string) *MockConfigProvider_SignKey_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConfigProvider_SignKey_Call) RunAndReturn(run func() string) *MockConfigProvider_SignKey_Call {
	_c.Call.Return(run)
	return _c
}
