// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package server

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockConfigProvider creates a new instance of MockConfigProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigProvider {
	mock := &MockConfigProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfigProvider is an autogenerated mock type for the ConfigProvider type
type MockConfigProvider struct {
	mock.Mock
}

type MockConfigProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigProvider) EXPECT() *MockConfigProvider_Expecter {
	return &MockConfigProvider_Expecter{mock: &_m.Mock}
}

// Address provides a mock function for the type MockConfigProvider
func (_mock *MockConfigProvider) Address() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Address")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfigProvider_Address_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Address'
type MockConfigProvider_Address_Call struct {
	*mock.Call
}

// Address is a helper method to define mock.On call
func (_e *MockConfigProvider_Expecter) Address() *MockConfigProvider_Address_Call {
	return &MockConfigProvider_Address_Call{Call: _e.mock.On("Address")}
}

func (_c *MockConfigProvider_Address_Call) Run(run func()) *MockConfigProvider_Address_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigProvider_Address_Call) Return(s string) *MockConfigProvider_Address_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConfigProvider_Address_Call) RunAndReturn(run func() string) *MockConfigProvider_Address_Call {
	_c.Call.Return(run)
	return _c
}

// FileStoragePath provides a mock function for the type MockConfigProvider
func (_mock *MockConfigProvider) FileStoragePath() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FileStoragePath")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfigProvider_FileStoragePath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FileStoragePath'
type MockConfigProvider_FileStoragePath_Call struct {
	*mock.Call
}

// FileStoragePath is a helper method to define mock.On call
func (_e *MockConfigProvider_Expecter) FileStoragePath() *MockConfigProvider_FileStoragePath_Call {
	return &MockConfigProvider_FileStoragePath_Call{Call: _e.mock.On("FileStoragePath")}
}

func (_c *MockConfigProvider_FileStoragePath_Call) Run(run func()) *MockConfigProvider_FileStoragePath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigProvider_FileStoragePath_Call) Return(s string) *MockConfigProvider_FileStoragePath_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConfigProvider_FileStoragePath_Call) RunAndReturn(run func() string) *MockConfigProvider_FileStoragePath_Call {
	_c.Call.Return(run)
	return _c
}

// Restore provides a mock function for the type MockConfigProvider
func (_mock *MockConfigProvider) Restore() *bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 *bool
	if returnFunc, ok := ret.Get(0).(func() *bool); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bool)
		}
	}
	return r0
}

// MockConfigProvider_Restore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restore'
type MockConfigProvider_Restore_Call struct {
	*mock.Call
}

// Restore is a helper method to define mock.On call
func (_e *MockConfigProvider_Expecter) Restore() *MockConfigProvider_Restore_Call {
	return &MockConfigProvider_Restore_Call{Call: _e.mock.On("Restore")}
}

func (_c *MockConfigProvider_Restore_Call) Run(run func()) *MockConfigProvider_Restore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigProvider_Restore_Call) Return(b *bool) *MockConfigProvider_Restore_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockConfigProvider_Restore_Call) RunAndReturn(run func() *bool) *MockConfigProvider_Restore_Call {
	_c.Call.Return(run)
	return _c
}

// StoreInterval provides a mock function for the type MockConfigProvider
func (_mock *MockConfigProvider) StoreInterval() *time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for StoreInterval")
	}

	var r0 *time.Duration
	if returnFunc, ok := ret.Get(0).(func() *time.Duration); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*time.Duration)
		}
	}
	return r0
}

// MockConfigProvider_StoreInterval_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreInterval'
type MockConfigProvider_StoreInterval_Call struct {
	*mock.Call
}

// StoreInterval is a helper method to define mock.On call
func (_e *MockConfigProvider_Expecter) StoreInterval() *MockConfigProvider_StoreInterval_Call {
	return &MockConfigProvider_StoreInterval_Call{Call: _e.mock.On("StoreInterval")}
}

func (_c *MockConfigProvider_StoreInterval_Call) Run(run func()) *MockConfigProvider_StoreInterval_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigProvider_StoreInterval_Call) Return(duration *time.Duration) *MockConfigProvider_StoreInterval_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockConfigProvider_StoreInterval_Call) RunAndReturn(run func() *time.Duration) *MockConfigProvider_StoreInterval_Call {
	_c.Call.Return(run)
	return _c
}
