CREATE TABLE IF NOT EXISTS metric (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id >= 0),
    metric_id VARCHAR(100) NOT NULL,
    m_type VARCHAR(20) NOT NULL,
    delta BIGINT,
    value DOUBLE PRECISION,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_metric UNIQUE (metric_id, m_type)
);

COMMENT ON COLUMN metric.id IS 'Уникальный идентификатор метрики, автоинкремент';
COMMENT ON COLUMN metric.metric_id IS 'Имя метрики (например, "cpu_usage" или "poll_count")';
COMMENT ON COLUMN metric.m_type IS 'Тип метрики: "gauge" или "counter"';
COMMENT ON COLUMN metric.delta IS 'Приращение для счётчика (counter), null для gauge';
COMMENT ON COLUMN metric.value IS 'Текущее значение для gauge, null для counter';
COMMENT ON COLUMN metric.created_at IS 'Временная метка создания записи';
COMMENT ON COLUMN metric.updated_at IS 'Временная метка последнего обновления записи';

CREATE INDEX idx_metric_m_type ON metric (m_type);