// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package metric

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// CounterAccumulative provides a mock function for the type MockStorage
func (_mock *MockStorage) CounterAccumulative() map[string]int64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CounterAccumulative")
	}

	var r0 map[string]int64
	if returnFunc, ok := ret.Get(0).(func() map[string]int64); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int64)
		}
	}
	return r0
}

// MockStorage_CounterAccumulative_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CounterAccumulative'
type MockStorage_CounterAccumulative_Call struct {
	*mock.Call
}

// CounterAccumulative is a helper method to define mock.On call
func (_e *MockStorage_Expecter) CounterAccumulative() *MockStorage_CounterAccumulative_Call {
	return &MockStorage_CounterAccumulative_Call{Call: _e.mock.On("CounterAccumulative")}
}

func (_c *MockStorage_CounterAccumulative_Call) Run(run func()) *MockStorage_CounterAccumulative_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_CounterAccumulative_Call) Return(stringToInt64 map[string]int64) *MockStorage_CounterAccumulative_Call {
	_c.Call.Return(stringToInt64)
	return _c
}

func (_c *MockStorage_CounterAccumulative_Call) RunAndReturn(run func() map[string]int64) *MockStorage_CounterAccumulative_Call {
	_c.Call.Return(run)
	return _c
}

// CounterAccumulativeByName provides a mock function for the type MockStorage
func (_mock *MockStorage) CounterAccumulativeByName(name string) (int64, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for CounterAccumulativeByName")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (int64, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) int64); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_CounterAccumulativeByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CounterAccumulativeByName'
type MockStorage_CounterAccumulativeByName_Call struct {
	*mock.Call
}

// CounterAccumulativeByName is a helper method to define mock.On call
//   - name string
func (_e *MockStorage_Expecter) CounterAccumulativeByName(name any) *MockStorage_CounterAccumulativeByName_Call {
	return &MockStorage_CounterAccumulativeByName_Call{Call: _e.mock.On("CounterAccumulativeByName", name)}
}

func (_c *MockStorage_CounterAccumulativeByName_Call) Run(run func(name string)) *MockStorage_CounterAccumulativeByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorage_CounterAccumulativeByName_Call) Return(n int64, err error) *MockStorage_CounterAccumulativeByName_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStorage_CounterAccumulativeByName_Call) RunAndReturn(run func(name string) (int64, error)) *MockStorage_CounterAccumulativeByName_Call {
	_c.Call.Return(run)
	return _c
}

// CounterAdd provides a mock function for the type MockStorage
func (_mock *MockStorage) CounterAdd(name string, value int64) {
	_mock.Called(name, value)
	return
}

// MockStorage_CounterAdd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CounterAdd'
type MockStorage_CounterAdd_Call struct {
	*mock.Call
}

// CounterAdd is a helper method to define mock.On call
//   - name string
//   - value int64
func (_e *MockStorage_Expecter) CounterAdd(name any, value any) *MockStorage_CounterAdd_Call {
	return &MockStorage_CounterAdd_Call{Call: _e.mock.On("CounterAdd", name, value)}
}

func (_c *MockStorage_CounterAdd_Call) Run(run func(name string, value int64)) *MockStorage_CounterAdd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_CounterAdd_Call) Return() *MockStorage_CounterAdd_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStorage_CounterAdd_Call) RunAndReturn(run func(name string, value int64)) *MockStorage_CounterAdd_Call {
	_c.Run(run)
	return _c
}

// Gauge provides a mock function for the type MockStorage
func (_mock *MockStorage) Gauge() map[string]float64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Gauge")
	}

	var r0 map[string]float64
	if returnFunc, ok := ret.Get(0).(func() map[string]float64); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]float64)
		}
	}
	return r0
}

// MockStorage_Gauge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Gauge'
type MockStorage_Gauge_Call struct {
	*mock.Call
}

// Gauge is a helper method to define mock.On call
func (_e *MockStorage_Expecter) Gauge() *MockStorage_Gauge_Call {
	return &MockStorage_Gauge_Call{Call: _e.mock.On("Gauge")}
}

func (_c *MockStorage_Gauge_Call) Run(run func()) *MockStorage_Gauge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_Gauge_Call) Return(stringToFloat64 map[string]float64) *MockStorage_Gauge_Call {
	_c.Call.Return(stringToFloat64)
	return _c
}

func (_c *MockStorage_Gauge_Call) RunAndReturn(run func() map[string]float64) *MockStorage_Gauge_Call {
	_c.Call.Return(run)
	return _c
}

// GaugeByName provides a mock function for the type MockStorage
func (_mock *MockStorage) GaugeByName(name string) (float64, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GaugeByName")
	}

	var r0 float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (float64, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) float64); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(float64)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_GaugeByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GaugeByName'
type MockStorage_GaugeByName_Call struct {
	*mock.Call
}

// GaugeByName is a helper method to define mock.On call
//   - name string
func (_e *MockStorage_Expecter) GaugeByName(name any) *MockStorage_GaugeByName_Call {
	return &MockStorage_GaugeByName_Call{Call: _e.mock.On("GaugeByName", name)}
}

func (_c *MockStorage_GaugeByName_Call) Run(run func(name string)) *MockStorage_GaugeByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorage_GaugeByName_Call) Return(f float64, err error) *MockStorage_GaugeByName_Call {
	_c.Call.Return(f, err)
	return _c
}

func (_c *MockStorage_GaugeByName_Call) RunAndReturn(run func(name string) (float64, error)) *MockStorage_GaugeByName_Call {
	_c.Call.Return(run)
	return _c
}

// GaugeUpdate provides a mock function for the type MockStorage
func (_mock *MockStorage) GaugeUpdate(name string, value float64) {
	_mock.Called(name, value)
	return
}

// MockStorage_GaugeUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GaugeUpdate'
type MockStorage_GaugeUpdate_Call struct {
	*mock.Call
}

// GaugeUpdate is a helper method to define mock.On call
//   - name string
//   - value float64
func (_e *MockStorage_Expecter) GaugeUpdate(name any, value any) *MockStorage_GaugeUpdate_Call {
	return &MockStorage_GaugeUpdate_Call{Call: _e.mock.On("GaugeUpdate", name, value)}
}

func (_c *MockStorage_GaugeUpdate_Call) Run(run func(name string, value float64)) *MockStorage_GaugeUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 float64
		if args[1] != nil {
			arg1 = args[1].(float64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_GaugeUpdate_Call) Return() *MockStorage_GaugeUpdate_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStorage_GaugeUpdate_Call) RunAndReturn(run func(name string, value float64)) *MockStorage_GaugeUpdate_Call {
	_c.Run(run)
	return _c
}

// Ping provides a mock function for the type MockStorage
func (_mock *MockStorage) Ping(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockStorage_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockStorage_Expecter) Ping(context1 any) *MockStorage_Ping_Call {
	return &MockStorage_Ping_Call{Call: _e.mock.On("Ping", context1)}
}

func (_c *MockStorage_Ping_Call) Run(run func(context1 context.Context)) *MockStorage_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorage_Ping_Call) Return(err error) *MockStorage_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_Ping_Call) RunAndReturn(run func(context1 context.Context) error) *MockStorage_Ping_Call {
	_c.Call.Return(run)
	return _c
}
