// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package metric

import (
	"context"

	"github.com/RAdevelop/ya_practicum-go-advanced-ext-metrics/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// Metric provides a mock function for the type MockStorage
func (_mock *MockStorage) Metric(ctx context.Context, metric *models.Metrics) (*models.Metrics, error) {
	ret := _mock.Called(ctx, metric)

	if len(ret) == 0 {
		panic("no return value specified for Metric")
	}

	var r0 *models.Metrics
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Metrics) (*models.Metrics, error)); ok {
		return returnFunc(ctx, metric)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Metrics) *models.Metrics); ok {
		r0 = returnFunc(ctx, metric)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Metrics)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.Metrics) error); ok {
		r1 = returnFunc(ctx, metric)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_Metric_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Metric'
type MockStorage_Metric_Call struct {
	*mock.Call
}

// Metric is a helper method to define mock.On call
//   - ctx context.Context
//   - metric *models.Metrics
func (_e *MockStorage_Expecter) Metric(ctx any, metric any) *MockStorage_Metric_Call {
	return &MockStorage_Metric_Call{Call: _e.mock.On("Metric", ctx, metric)}
}

func (_c *MockStorage_Metric_Call) Run(run func(ctx context.Context, metric *models.Metrics)) *MockStorage_Metric_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Metrics
		if args[1] != nil {
			arg1 = args[1].(*models.Metrics)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_Metric_Call) Return(metrics *models.Metrics, err error) *MockStorage_Metric_Call {
	_c.Call.Return(metrics, err)
	return _c
}

func (_c *MockStorage_Metric_Call) RunAndReturn(run func(ctx context.Context, metric *models.Metrics) (*models.Metrics, error)) *MockStorage_Metric_Call {
	_c.Call.Return(run)
	return _c
}

// MetricList provides a mock function for the type MockStorage
func (_mock *MockStorage) MetricList(ctx context.Context, metricType string) ([]models.Metrics, error) {
	ret := _mock.Called(ctx, metricType)

	if len(ret) == 0 {
		panic("no return value specified for MetricList")
	}

	var r0 []models.Metrics
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]models.Metrics, error)); ok {
		return returnFunc(ctx, metricType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []models.Metrics); ok {
		r0 = returnFunc(ctx, metricType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Metrics)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, metricType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_MetricList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MetricList'
type MockStorage_MetricList_Call struct {
	*mock.Call
}

// MetricList is a helper method to define mock.On call
//   - ctx context.Context
//   - metricType string
func (_e *MockStorage_Expecter) MetricList(ctx any, metricType any) *MockStorage_MetricList_Call {
	return &MockStorage_MetricList_Call{Call: _e.mock.On("MetricList", ctx, metricType)}
}

func (_c *MockStorage_MetricList_Call) Run(run func(ctx context.Context, metricType string)) *MockStorage_MetricList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_MetricList_Call) Return(metricss []models.Metrics, err error) *MockStorage_MetricList_Call {
	_c.Call.Return(metricss, err)
	return _c
}

func (_c *MockStorage_MetricList_Call) RunAndReturn(run func(ctx context.Context, metricType string) ([]models.Metrics, error)) *MockStorage_MetricList_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockStorage
func (_mock *MockStorage) Ping(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockStorage_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockStorage_Expecter) Ping(context1 any) *MockStorage_Ping_Call {
	return &MockStorage_Ping_Call{Call: _e.mock.On("Ping", context1)}
}

func (_c *MockStorage_Ping_Call) Run(run func(context1 context.Context)) *MockStorage_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorage_Ping_Call) Return(err error) *MockStorage_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_Ping_Call) RunAndReturn(run func(context1 context.Context) error) *MockStorage_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBatch provides a mock function for the type MockStorage
func (_mock *MockStorage) UpdateBatch(ctx context.Context, metrics []models.Metrics) error {
	ret := _mock.Called(ctx, metrics)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []models.Metrics) error); ok {
		r0 = returnFunc(ctx, metrics)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_UpdateBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBatch'
type MockStorage_UpdateBatch_Call struct {
	*mock.Call
}

// UpdateBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - metrics []models.Metrics
func (_e *MockStorage_Expecter) UpdateBatch(ctx any, metrics any) *MockStorage_UpdateBatch_Call {
	return &MockStorage_UpdateBatch_Call{Call: _e.mock.On("UpdateBatch", ctx, metrics)}
}

func (_c *MockStorage_UpdateBatch_Call) Run(run func(ctx context.Context, metrics []models.Metrics)) *MockStorage_UpdateBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []models.Metrics
		if args[1] != nil {
			arg1 = args[1].([]models.Metrics)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_UpdateBatch_Call) Return(err error) *MockStorage_UpdateBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_UpdateBatch_Call) RunAndReturn(run func(ctx context.Context, metrics []models.Metrics) error) *MockStorage_UpdateBatch_Call {
	_c.Call.Return(run)
	return _c
}
