// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package metric

import (
	"context"

	"github.com/RAdevelop/ya_practicum-go-advanced-ext-metrics/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// CounterAccumulative provides a mock function for the type MockStorage
func (_mock *MockStorage) CounterAccumulative(ctx context.Context) ([]models.Metrics, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CounterAccumulative")
	}

	var r0 []models.Metrics
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.Metrics, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.Metrics); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Metrics)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_CounterAccumulative_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CounterAccumulative'
type MockStorage_CounterAccumulative_Call struct {
	*mock.Call
}

// CounterAccumulative is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStorage_Expecter) CounterAccumulative(ctx any) *MockStorage_CounterAccumulative_Call {
	return &MockStorage_CounterAccumulative_Call{Call: _e.mock.On("CounterAccumulative", ctx)}
}

func (_c *MockStorage_CounterAccumulative_Call) Run(run func(ctx context.Context)) *MockStorage_CounterAccumulative_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorage_CounterAccumulative_Call) Return(metricss []models.Metrics, err error) *MockStorage_CounterAccumulative_Call {
	_c.Call.Return(metricss, err)
	return _c
}

func (_c *MockStorage_CounterAccumulative_Call) RunAndReturn(run func(ctx context.Context) ([]models.Metrics, error)) *MockStorage_CounterAccumulative_Call {
	_c.Call.Return(run)
	return _c
}

// Gauge provides a mock function for the type MockStorage
func (_mock *MockStorage) Gauge(ctx context.Context) ([]models.Metrics, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Gauge")
	}

	var r0 []models.Metrics
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.Metrics, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.Metrics); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Metrics)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_Gauge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Gauge'
type MockStorage_Gauge_Call struct {
	*mock.Call
}

// Gauge is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStorage_Expecter) Gauge(ctx any) *MockStorage_Gauge_Call {
	return &MockStorage_Gauge_Call{Call: _e.mock.On("Gauge", ctx)}
}

func (_c *MockStorage_Gauge_Call) Run(run func(ctx context.Context)) *MockStorage_Gauge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorage_Gauge_Call) Return(metricss []models.Metrics, err error) *MockStorage_Gauge_Call {
	_c.Call.Return(metricss, err)
	return _c
}

func (_c *MockStorage_Gauge_Call) RunAndReturn(run func(ctx context.Context) ([]models.Metrics, error)) *MockStorage_Gauge_Call {
	_c.Call.Return(run)
	return _c
}

// Metric provides a mock function for the type MockStorage
func (_mock *MockStorage) Metric(context1 context.Context, metrics *models.Metrics) (*models.Metrics, error) {
	ret := _mock.Called(context1, metrics)

	if len(ret) == 0 {
		panic("no return value specified for Metric")
	}

	var r0 *models.Metrics
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Metrics) (*models.Metrics, error)); ok {
		return returnFunc(context1, metrics)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Metrics) *models.Metrics); ok {
		r0 = returnFunc(context1, metrics)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Metrics)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.Metrics) error); ok {
		r1 = returnFunc(context1, metrics)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_Metric_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Metric'
type MockStorage_Metric_Call struct {
	*mock.Call
}

// Metric is a helper method to define mock.On call
//   - context1 context.Context
//   - metrics *models.Metrics
func (_e *MockStorage_Expecter) Metric(context1 any, metrics any) *MockStorage_Metric_Call {
	return &MockStorage_Metric_Call{Call: _e.mock.On("Metric", context1, metrics)}
}

func (_c *MockStorage_Metric_Call) Run(run func(context1 context.Context, metrics *models.Metrics)) *MockStorage_Metric_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Metrics
		if args[1] != nil {
			arg1 = args[1].(*models.Metrics)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_Metric_Call) Return(metrics1 *models.Metrics, err error) *MockStorage_Metric_Call {
	_c.Call.Return(metrics1, err)
	return _c
}

func (_c *MockStorage_Metric_Call) RunAndReturn(run func(context1 context.Context, metrics *models.Metrics) (*models.Metrics, error)) *MockStorage_Metric_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockStorage
func (_mock *MockStorage) Ping(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockStorage_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockStorage_Expecter) Ping(context1 any) *MockStorage_Ping_Call {
	return &MockStorage_Ping_Call{Call: _e.mock.On("Ping", context1)}
}

func (_c *MockStorage_Ping_Call) Run(run func(context1 context.Context)) *MockStorage_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorage_Ping_Call) Return(err error) *MockStorage_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_Ping_Call) RunAndReturn(run func(context1 context.Context) error) *MockStorage_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBatch provides a mock function for the type MockStorage
func (_mock *MockStorage) UpdateBatch(ctx context.Context, metrics []models.Metrics) error {
	ret := _mock.Called(ctx, metrics)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []models.Metrics) error); ok {
		r0 = returnFunc(ctx, metrics)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_UpdateBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBatch'
type MockStorage_UpdateBatch_Call struct {
	*mock.Call
}

// UpdateBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - metrics []models.Metrics
func (_e *MockStorage_Expecter) UpdateBatch(ctx any, metrics any) *MockStorage_UpdateBatch_Call {
	return &MockStorage_UpdateBatch_Call{Call: _e.mock.On("UpdateBatch", ctx, metrics)}
}

func (_c *MockStorage_UpdateBatch_Call) Run(run func(ctx context.Context, metrics []models.Metrics)) *MockStorage_UpdateBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []models.Metrics
		if args[1] != nil {
			arg1 = args[1].([]models.Metrics)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_UpdateBatch_Call) Return(err error) *MockStorage_UpdateBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_UpdateBatch_Call) RunAndReturn(run func(ctx context.Context, metrics []models.Metrics) error) *MockStorage_UpdateBatch_Call {
	_c.Call.Return(run)
	return _c
}
