// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package snapshot

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockAble creates a new instance of MockAble. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAble(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAble {
	mock := &MockAble{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAble is an autogenerated mock type for the Able type
type MockAble struct {
	mock.Mock
}

type MockAble_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAble) EXPECT() *MockAble_Expecter {
	return &MockAble_Expecter{mock: &_m.Mock}
}

// Load provides a mock function for the type MockAble
func (_mock *MockAble) Load() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAble_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockAble_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
func (_e *MockAble_Expecter) Load() *MockAble_Load_Call {
	return &MockAble_Load_Call{Call: _e.mock.On("Load")}
}

func (_c *MockAble_Load_Call) Run(run func()) *MockAble_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAble_Load_Call) Return(err error) *MockAble_Load_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAble_Load_Call) RunAndReturn(run func() error) *MockAble_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockAble
func (_mock *MockAble) Save() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAble_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockAble_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
func (_e *MockAble_Expecter) Save() *MockAble_Save_Call {
	return &MockAble_Save_Call{Call: _e.mock.On("Save")}
}

func (_c *MockAble_Save_Call) Run(run func()) *MockAble_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAble_Save_Call) Return(err error) *MockAble_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAble_Save_Call) RunAndReturn(run func() error) *MockAble_Save_Call {
	_c.Call.Return(run)
	return _c
}
