// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package db

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockConfigProvider creates a new instance of MockConfigProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigProvider {
	mock := &MockConfigProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfigProvider is an autogenerated mock type for the ConfigProvider type
type MockConfigProvider struct {
	mock.Mock
}

type MockConfigProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigProvider) EXPECT() *MockConfigProvider_Expecter {
	return &MockConfigProvider_Expecter{mock: &_m.Mock}
}

// DSN provides a mock function for the type MockConfigProvider
func (_mock *MockConfigProvider) DSN() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DSN")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfigProvider_DSN_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DSN'
type MockConfigProvider_DSN_Call struct {
	*mock.Call
}

// DSN is a helper method to define mock.On call
func (_e *MockConfigProvider_Expecter) DSN() *MockConfigProvider_DSN_Call {
	return &MockConfigProvider_DSN_Call{Call: _e.mock.On("DSN")}
}

func (_c *MockConfigProvider_DSN_Call) Run(run func()) *MockConfigProvider_DSN_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigProvider_DSN_Call) Return(s string) *MockConfigProvider_DSN_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConfigProvider_DSN_Call) RunAndReturn(run func() string) *MockConfigProvider_DSN_Call {
	_c.Call.Return(run)
	return _c
}

// MaxConnIdleTime provides a mock function for the type MockConfigProvider
func (_mock *MockConfigProvider) MaxConnIdleTime() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MaxConnIdleTime")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockConfigProvider_MaxConnIdleTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MaxConnIdleTime'
type MockConfigProvider_MaxConnIdleTime_Call struct {
	*mock.Call
}

// MaxConnIdleTime is a helper method to define mock.On call
func (_e *MockConfigProvider_Expecter) MaxConnIdleTime() *MockConfigProvider_MaxConnIdleTime_Call {
	return &MockConfigProvider_MaxConnIdleTime_Call{Call: _e.mock.On("MaxConnIdleTime")}
}

func (_c *MockConfigProvider_MaxConnIdleTime_Call) Run(run func()) *MockConfigProvider_MaxConnIdleTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigProvider_MaxConnIdleTime_Call) Return(duration time.Duration) *MockConfigProvider_MaxConnIdleTime_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockConfigProvider_MaxConnIdleTime_Call) RunAndReturn(run func() time.Duration) *MockConfigProvider_MaxConnIdleTime_Call {
	_c.Call.Return(run)
	return _c
}

// MaxConnLifetime provides a mock function for the type MockConfigProvider
func (_mock *MockConfigProvider) MaxConnLifetime() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MaxConnLifetime")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockConfigProvider_MaxConnLifetime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MaxConnLifetime'
type MockConfigProvider_MaxConnLifetime_Call struct {
	*mock.Call
}

// MaxConnLifetime is a helper method to define mock.On call
func (_e *MockConfigProvider_Expecter) MaxConnLifetime() *MockConfigProvider_MaxConnLifetime_Call {
	return &MockConfigProvider_MaxConnLifetime_Call{Call: _e.mock.On("MaxConnLifetime")}
}

func (_c *MockConfigProvider_MaxConnLifetime_Call) Run(run func()) *MockConfigProvider_MaxConnLifetime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigProvider_MaxConnLifetime_Call) Return(duration time.Duration) *MockConfigProvider_MaxConnLifetime_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockConfigProvider_MaxConnLifetime_Call) RunAndReturn(run func() time.Duration) *MockConfigProvider_MaxConnLifetime_Call {
	_c.Call.Return(run)
	return _c
}

// MaxConns provides a mock function for the type MockConfigProvider
func (_mock *MockConfigProvider) MaxConns() int32 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MaxConns")
	}

	var r0 int32
	if returnFunc, ok := ret.Get(0).(func() int32); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int32)
	}
	return r0
}

// MockConfigProvider_MaxConns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MaxConns'
type MockConfigProvider_MaxConns_Call struct {
	*mock.Call
}

// MaxConns is a helper method to define mock.On call
func (_e *MockConfigProvider_Expecter) MaxConns() *MockConfigProvider_MaxConns_Call {
	return &MockConfigProvider_MaxConns_Call{Call: _e.mock.On("MaxConns")}
}

func (_c *MockConfigProvider_MaxConns_Call) Run(run func()) *MockConfigProvider_MaxConns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigProvider_MaxConns_Call) Return(n int32) *MockConfigProvider_MaxConns_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockConfigProvider_MaxConns_Call) RunAndReturn(run func() int32) *MockConfigProvider_MaxConns_Call {
	_c.Call.Return(run)
	return _c
}

// MinConns provides a mock function for the type MockConfigProvider
func (_mock *MockConfigProvider) MinConns() int32 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MinConns")
	}

	var r0 int32
	if returnFunc, ok := ret.Get(0).(func() int32); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int32)
	}
	return r0
}

// MockConfigProvider_MinConns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MinConns'
type MockConfigProvider_MinConns_Call struct {
	*mock.Call
}

// MinConns is a helper method to define mock.On call
func (_e *MockConfigProvider_Expecter) MinConns() *MockConfigProvider_MinConns_Call {
	return &MockConfigProvider_MinConns_Call{Call: _e.mock.On("MinConns")}
}

func (_c *MockConfigProvider_MinConns_Call) Run(run func()) *MockConfigProvider_MinConns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigProvider_MinConns_Call) Return(n int32) *MockConfigProvider_MinConns_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockConfigProvider_MinConns_Call) RunAndReturn(run func() int32) *MockConfigProvider_MinConns_Call {
	_c.Call.Return(run)
	return _c
}
